name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: "pip"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest pytest-cov

    - name: Run pre‑commit checks
      uses: pre-commit/action@v3.0.0
      with:
        extra_args: --all-files --show-diff-on-failure

    - name: Run pytest
      env:
        CASAVI_API_KEY: fake_key
        CASAVI_API_SECRET: fake_secret
      run: |
        pytest --cov=src --cov-report=xml --quiet
